version: "3.8"

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "5001:5001"   # API HTTP
      - "8080:8080"   # Gateway HTTP
      - "4001:4001"   # Swarm TCP
    volumes:
      - ipfs-data:/data/ipfs
    user: "0:0"
    environment:
      - IPFS_PATH=/data/ipfs
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ipfs init --profile=server || true &&
      ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001 &&
      ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080 &&
      ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '[\"*\"]' &&
      ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '[\"GET\", \"POST\", \"PUT\", \"DELETE\"]' &&
      ipfs config --json API.HTTPHeaders.Access-Control-Allow-Headers '[\"Authorization\", \"Content-Type\"]' &&
      ipfs daemon --migrate"

volumes:
  ipfs-data: